### ISSUE TITLE
assert in the init function

### ISSUE THREAD

**Issue by MarineLasbleis** [MarineLasbleis/coreevolution#2]
These asserts: 
        # Check if the IC radius and melting temperature I find correspond to the ones in the planet structure
        if self.planet.S == 0:
            assert int(self.planet.TL0) == int(self.planet.TL0_0), int(
                self.planet.r_IC_0) == int(self.planet.r_IC_0)
        elif self.planet.S == 0.05:
            assert int(self.planet.TL0) == int(self.planet.TL0_005), int(
                self.planet.r_IC_0) == int(self.planet.r_IC_005)
        elif self.planet.S == 0.11:
            assert int(self.planet.TL0) == int(self.planet.TL0_011), int(
                self.planet.r_IC_0) == int(self.planet.r_IC_011)

Should we keep them? We need to rewrite them when we change the T liquidus, so it's quite heavy. 
Maybe remove it in another function (that woul then be rewritten when a new class is made, inheriting functions from Evolution class?)

**Comment by irenebonati** [comment]
Yes, they can be removed. These asserts never gave me issues so far, so it's safe to remove them for now.

**Comment by MarineLasbleis** [comment]
Great! I'll do that then :-)
